openapi: 3.0.0
info:
  title: API Bibliothèque UHA
  description: API de gestion avec authentification par Magic Link (Email uniquement).
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Serveur de développement local

paths:
  /auth/register:
    post:
      summary: Inscription d'un nouvel utilisateur
      tags: [Authentification]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, nom, prenom]
              properties:
                email: { type: string, example: "etudiant@uha.fr" }
                nom: { type: string, example: "Dupont" }
                prenom: { type: string, example: "Jean" }
                role: { type: string, enum: [ETUDIANT, ENSEIGNANT, BIBLIOTHECAIRE] }
      responses:
        '201':
          description: Utilisateur créé (statut ACTIF par défaut)
        '400':
          description: Erreur lors de l'inscription

  /auth/login:
    post:
      summary: Connexion par Email (Magic Link)
      tags: [Authentification]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email: { type: string, example: "etudiant@uha.fr" }
      responses:
        '200':
          description: Email de connexion envoyé
        '401':
          description: Erreur d'envoi

  /api/books:
    get:
      summary: Liste tous les livres du catalogue
      tags:
        - Catalogue
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: "Recherche par titre, auteur ou ISBN"

        - in: query
          name: categorie
          schema:
            type: string
          description: "Filtrer par catégorie (ex: Roman, Dystopie)"

        - in: query
          name: sort
          schema:
            type: string
            enum:
              - auteur
              - disponibilite
              - titre
          description: "Trier les résultats"

      responses:
        '200':
          description: Liste des livres
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Livre'
  /api/books/{isbn}/dispo:
    get:
      summary: Récupère le stock réel pour un ISBN précis
      tags: [Catalogue]
      parameters:
        - in: path
          name: isbn
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stock actuel
          content:
            application/json:
              schema:
                type: object
                properties:
                  isbn: { type: string }
                  nb_disponible: { type: integer }
                  disponible: { type: boolean }
  /emprunts:
    get:
      summary: Liste les emprunts
      tags: [Emprunts]
      parameters:
        - in: query
          name: utilisateurId
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Emprunt'
                  
    post:
      summary: Effectuer un nouvel emprunt (réservation)
      tags: [Emprunts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id_utilisateur, isbn]
              properties:
                id_utilisateur: 
                  type: string
                  format: uuid
                  example: "550e8400-e29b-41d4-a716-446655440000"
                isbn: 
                  type: string
                  example: "9782070415793"
      responses:
        '201':
          description: Emprunt créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  emprunt: { $ref: '#/components/schemas/Emprunt' }
        '400':
          description: Aucun exemplaire disponible ou données manquantes
        '500':
          description: Erreur serveur

components:
  schemas:
    Utilisateur:
      type: object
      properties:
        id: { type: string, format: uuid }
        nom: { type: string }
        prenom: { type: string }
        email: { type: string }
        role: { type: string }
        statut: { type: string, example: "ACTIF" }

    Livre:
      type: object
      required: [isbn, titre, auteur, categorie, annee]
      properties:
        isbn: { type: string }
        titre: { type: string }
        auteur: { type: string }
        categorie: { type: string }
        annee: { type: integer }
        est_disponible: { type: boolean }
        exemplaire:
          type: object
          properties:
            id_exemplaire: { type: string, format: uuid }
            disponibilite: { type: boolean }
            etat: { type: string }
            localisation: { type: string }

    Emprunt:
      type: object
      properties:
        id: { type: integer }
        dateEmprunt: { type: string, format: date }
        dateRetourPrevue: { type: string, format: date }
        estRendu: { type: boolean }
        utilisateurId: { type: string, format: uuid }
        exemplaireId: { type: integer }